name: gaussian_splatting
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=11.6
  - cuda=12.0
  - plyfile
  - python=3.8
  - pip=22.3.1
  # - pytorch=1.12.1
  - pytorch=2.0.0
  # - torchaudio=0.12.1
  # - torchvision=0.13.1
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization --install-option="--no-build-isolation"  
    # - submodules/simple-knn
    - submodules/fused-ssim --install-option="--no-build-isolation"
    - opencv-python
    - joblib
